# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.initrd.systemd.network.wait-online.enable = true;
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/82ed2f70-c895-4fea-bce7-415a513e0ccf";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1ba81526-3e9e-4486-aaa1-4dbf3c8c3663".device = "/dev/disk/by-uuid/1ba81526-3e9e-4486-aaa1-4dbf3c8c3663";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E0CA-2CC4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2414641a-ab5f-4683-921b-e4d46f4e78bd"; }
    ];



  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
